[build]
cmd = "go build -o build/server cmd/main.go"
bin = "build/server"
#exclude_dir = ["web", "data","node_modules"]
#include_dir=["lib"]
include_file=["lib/server/http/index.gohtml", ".air.toml"]
